//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace felix.BlishEmotes.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("felix.BlishEmotes.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open emotes list.
        /// </summary>
        public static string cornerIcon_tooltip {
            get {
                return ResourceManager.GetString("cornerIcon_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string settings_button {
            get {
                return ResourceManager.GetString("settings_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Keybinds.
        /// </summary>
        public static string settings_emotesKeybindSubCollection {
            get {
                return ResourceManager.GetString("settings_emotesKeybindSubCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Corner Icon.
        /// </summary>
        public static string settings_global_hideCornerIcon {
            get {
                return ResourceManager.GetString("settings_global_hideCornerIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle emote list.
        /// </summary>
        public static string settings_global_keybindToggleEmoteList {
            get {
                return ResourceManager.GetString("settings_global_keybindToggleEmoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split into categories.
        /// </summary>
        public static string settings_global_useCategories {
            get {
                return ResourceManager.GetString("settings_global_useCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string settings_ui_global_tab {
            get {
                return ResourceManager.GetString("settings_ui_global_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes Settings.
        /// </summary>
        public static string settings_ui_title {
            get {
                return ResourceManager.GetString("settings_ui_title", resourceCulture);
            }
        }
    }
}
