//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace felix.BlishEmotes.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("felix.BlishEmotes.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open emotes list.
        /// </summary>
        public static string cornerIcon_tooltip {
            get {
                return ResourceManager.GetString("cornerIcon_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string emote_categoryFavourite {
            get {
                return ResourceManager.GetString("emote_categoryFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing emotes.
        /// </summary>
        public static string emote_synchronizeActive {
            get {
                return ResourceManager.GetString("emote_synchronizeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target emotes.
        /// </summary>
        public static string emote_targetingActive {
            get {
                return ResourceManager.GetString("emote_targetingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string settings_button {
            get {
                return ResourceManager.GetString("settings_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Keybinds.
        /// </summary>
        public static string settings_emotesKeybindSubCollection {
            get {
                return ResourceManager.GetString("settings_emotesKeybindSubCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Corner Icon.
        /// </summary>
        public static string settings_global_hideCornerIcon {
            get {
                return ResourceManager.GetString("settings_global_hideCornerIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle emote list.
        /// </summary>
        public static string settings_global_keybindToggleEmoteList {
            get {
                return ResourceManager.GetString("settings_global_keybindToggleEmoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Emote Toggle.
        /// </summary>
        public static string settings_global_keybindToggleSynchronize {
            get {
                return ResourceManager.GetString("settings_global_keybindToggleSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting Emote Toggle.
        /// </summary>
        public static string settings_global_keybindToggleTargeting {
            get {
                return ResourceManager.GetString("settings_global_keybindToggleTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable categories.
        /// </summary>
        public static string settings_global_useCategories {
            get {
                return ResourceManager.GetString("settings_global_useCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use radial menu.
        /// </summary>
        public static string settings_global_useRadialMenu {
            get {
                return ResourceManager.GetString("settings_global_useRadialMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action camera keybind.
        /// </summary>
        public static string settings_radial_actionCamKeybind {
            get {
                return ResourceManager.GetString("settings_radial_actionCamKeybind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display in radial menu.
        /// </summary>
        public static string settings_radial_emotesEnabled {
            get {
                return ResourceManager.GetString("settings_radial_emotesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon opacity.
        /// </summary>
        public static string settings_radial_iconOpacity {
            get {
                return ResourceManager.GetString("settings_radial_iconOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon size modifier.
        /// </summary>
        public static string settings_radial_iconSizeModifier {
            get {
                return ResourceManager.GetString("settings_radial_iconSizeModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled radius percentage.
        /// </summary>
        public static string settings_radial_innerRadiusPercentage {
            get {
                return ResourceManager.GetString("settings_radial_innerRadiusPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the radius where no emotes get selected in precentage of the radial radius.
        /// </summary>
        public static string settings_radial_innerRadiusPercentage_description {
            get {
                return ResourceManager.GetString("settings_radial_innerRadiusPercentage_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius modifier.
        /// </summary>
        public static string settings_radial_radiusModifier {
            get {
                return ResourceManager.GetString("settings_radial_radiusModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn at cursor.
        /// </summary>
        public static string settings_radial_spawnAtCursor {
            get {
                return ResourceManager.GetString("settings_radial_spawnAtCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote Hotkeys.
        /// </summary>
        public static string settings_ui_emoteHotkeys_tab {
            get {
                return ResourceManager.GetString("settings_ui_emoteHotkeys_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string settings_ui_global_tab {
            get {
                return ResourceManager.GetString("settings_ui_global_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes Settings.
        /// </summary>
        public static string settings_ui_title {
            get {
                return ResourceManager.GetString("settings_ui_title", resourceCulture);
            }
        }
    }
}
