//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace felix.BlishEmotes.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emotes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emotes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("felix.BlishEmotes.Strings.Emotes", typeof(Emotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beckon.
        /// </summary>
        internal static string beckon {
            get {
                return ResourceManager.GetString("beckon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bless.
        /// </summary>
        internal static string bless {
            get {
                return ResourceManager.GetString("bless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        internal static string bow {
            get {
                return ResourceManager.GetString("bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheer.
        /// </summary>
        internal static string cheer {
            get {
                return ResourceManager.GetString("cheer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cower.
        /// </summary>
        internal static string cower {
            get {
                return ResourceManager.GetString("cower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossarms.
        /// </summary>
        internal static string crossarms {
            get {
                return ResourceManager.GetString("crossarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cry.
        /// </summary>
        internal static string cry {
            get {
                return ResourceManager.GetString("cry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance.
        /// </summary>
        internal static string dance {
            get {
                return ResourceManager.GetString("dance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facepalm.
        /// </summary>
        internal static string facepalm {
            get {
                return ResourceManager.GetString("facepalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geargrind.
        /// </summary>
        internal static string geargrind {
            get {
                return ResourceManager.GetString("geargrind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroic.
        /// </summary>
        internal static string heroic {
            get {
                return ResourceManager.GetString("heroic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiss.
        /// </summary>
        internal static string hiss {
            get {
                return ResourceManager.GetString("hiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kneel.
        /// </summary>
        internal static string kneel {
            get {
                return ResourceManager.GetString("kneel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laugh.
        /// </summary>
        internal static string laugh {
            get {
                return ResourceManager.GetString("laugh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Juggle.
        /// </summary>
        internal static string magicjuggle {
            get {
                return ResourceManager.GetString("magicjuggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string paper {
            get {
                return ResourceManager.GetString("paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petal throw.
        /// </summary>
        internal static string petalthrow {
            get {
                return ResourceManager.GetString("petalthrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playdead.
        /// </summary>
        internal static string playdead {
            get {
                return ResourceManager.GetString("playdead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponder.
        /// </summary>
        internal static string ponder {
            get {
                return ResourceManager.GetString("ponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possessed.
        /// </summary>
        internal static string possessed {
            get {
                return ResourceManager.GetString("possessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read book.
        /// </summary>
        internal static string readbook {
            get {
                return ResourceManager.GetString("readbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        internal static string rock {
            get {
                return ResourceManager.GetString("rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rockout.
        /// </summary>
        internal static string rockout {
            get {
                return ResourceManager.GetString("rockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        internal static string sad {
            get {
                return ResourceManager.GetString("sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salute.
        /// </summary>
        internal static string salute {
            get {
                return ResourceManager.GetString("salute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scissors.
        /// </summary>
        internal static string scissors {
            get {
                return ResourceManager.GetString("scissors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serve.
        /// </summary>
        internal static string serve {
            get {
                return ResourceManager.GetString("serve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiver.
        /// </summary>
        internal static string shiver {
            get {
                return ResourceManager.GetString("shiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiver plus.
        /// </summary>
        internal static string shiverplus {
            get {
                return ResourceManager.GetString("shiverplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrug.
        /// </summary>
        internal static string shrug {
            get {
                return ResourceManager.GetString("shrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string shuffle {
            get {
                return ResourceManager.GetString("shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sip coffee.
        /// </summary>
        internal static string sipcoffee {
            get {
                return ResourceManager.GetString("sipcoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit.
        /// </summary>
        internal static string sit {
            get {
                return ResourceManager.GetString("sit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string sleep {
            get {
                return ResourceManager.GetString("sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string stretch {
            get {
                return ResourceManager.GetString("stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprised.
        /// </summary>
        internal static string surprised {
            get {
                return ResourceManager.GetString("surprised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        internal static string talk {
            get {
                return ResourceManager.GetString("talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string thanks {
            get {
                return ResourceManager.GetString("thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threaten.
        /// </summary>
        internal static string threaten {
            get {
                return ResourceManager.GetString("threaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unleash.
        /// </summary>
        internal static string unleash {
            get {
                return ResourceManager.GetString("unleash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave.
        /// </summary>
        internal static string wave {
            get {
                return ResourceManager.GetString("wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
