name: Build Blish Emotes

on:
  push:
    branches:
      - master
  
jobs:
  build-vs-solution:
    runs-on: windows-2019

    steps:
      - name: Test
        run: |
          echo "TEST 1"
          echo "TEST 2"
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore referenced packages
        run: msbuild ".\BlishEmotes.sln" -t:restore -p:RestorePackagesConfig=true

      - name: Build VS Solution
        run: msbuild ".\BlishEmotes.sln" -t:rebuild -property:Configuration=Release

      - name: Copy module up
        run: xcopy .\bin\x64\Release\BlishEmotes.bhm .
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BlishEmotes
          path: |
            .\BlishEmotes.bhm
            .\manifest.json
          retention-days: 5

  create-release:
    needs: build-vs-solution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: BlishEmotes
          path: ./

      - name: Extract version from manifest
        id: version_extractor
        run: |
          echo 'TEST'
          #echo 'MANIFEST_JSON<<EOF' >> $GITHUB_ENV
          #cat ./manifest.json >> $GITHUB_ENV
          #echo 'EOF' >> $GITHUB_ENV
          #echo '${{ env.MANIFEST_JSON }}'
          echo "PACKAGE_JSON=$(jq -c . < manifest.json)"
          # VER=${{ fromJson(env.MANIFEST_JSON).version }}
          # echo 'VERSION=$VER' >> GITHUB_OUTPUT

#      - name: Version readout test
#        run: echo '${{ steps.version_extractor.outputs.VERSION }}'

#      - name: Create tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          custom_tag: "0.0.0"

#      - name: Create release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.tag_version.outputs.new_tag }}
#          name: Release ${{ steps.tag_version.outputs.new_tag }}
#          artifacts: "./BlishEmotes.bhm"
