name: Build Blish Emotes

on:
  push:
    branches:
      - master
  
jobs:
  build-vs-solution:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore referenced packages
        run: msbuild ".\BlishEmotes.sln" -t:restore -p:RestorePackagesConfig=true

      - name: Build VS Solution
        run: msbuild ".\BlishEmotes.sln" -t:rebuild -property:Configuration=Release

      - name: Copy module up
        run: xcopy .\bin\x64\Release\BlishEmotes.bhm .
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BlishEmotes
          path: |
            .\BlishEmotes.bhm
            .\manifest.json
          retention-days: 5

  create-release:
    needs: build-vs-solution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: BlishEmotes
          path: ./

      - name: Read manifest json
        run: echo "MANIFEST_JSON=$(jq -c . < manifest.json)" >> "$GITHUB_ENV"

      - name: Extract version from manifest
        id: version_extractor
        run: |
          VER=${{ fromJson(env.MANIFEST_JSON).version }}
          echo 'VERSION=$VER' >> "$GITHUB_OUTPUT"

      - name: Version readout test
        run: echo '${{ steps.version_extractor.outputs.VERSION }}'
